extends RefCounted
## Unwired source declarations for the landed Néhma34 result.
const Equal=preload("res://src/content/opening_escape_definitions.gd")
const Fonts=preload("res://src/content/font_definitions.gd")
const Layouts=preload("res://src/content/declaration_layouts.gd")
const Void=preload("res://src/content/void_crystal_definitions.gd")
const VALUES:={"scope":"nehma_station_visit34","mission34":{"campaign_cursor":34,"kind":11,"station_id":30,"system_id":2,"story":true,"reward":0,"bonus":0,"briefing_events":[],"result_events":[{"speaker_id":1,"text_id":1980,"voice_event_id":364},{"speaker_id":0,"text_id":1981,"voice_event_id":365},{"speaker_id":1,"text_id":1982,"voice_event_id":371},{"speaker_id":0,"text_id":1983,"voice_event_id":372},{"speaker_id":1,"text_id":1984,"voice_event_id":373},{"speaker_id":0,"text_id":1985,"voice_event_id":374},{"speaker_id":1,"text_id":1986,"voice_event_id":375},{"speaker_id":0,"text_id":1987,"voice_event_id":376},{"speaker_id":1,"text_id":1988,"voice_event_id":377},{"speaker_id":0,"text_id":1989,"voice_event_id":378},{"speaker_id":1,"text_id":1990,"voice_event_id":366},{"speaker_id":0,"text_id":1991,"voice_event_id":367},{"speaker_id":1,"text_id":1992,"voice_event_id":368},{"speaker_id":0,"text_id":1993,"voice_event_id":369},{"speaker_id":1,"text_id":1994,"voice_event_id":370}],"completion":{"result_mode":1,"requires_landed_target":true,"completed_on_result_open":true,"intermediate_next_keeps_cursor":34,"final_next_requires_all_modal_acknowledgements":true,"final_next_advances_to_cursor":35,"reward_credits":0,"stays_landed_station_id":30,"cargo_or_equipment_change":false,"extra_blueprint_change":false,"extra_system_access_granted":false}},"world":{"authored_cast":[],"authored_radio_events":[],"selected_kind11_actor_count":0},"next_mission":{"campaign_cursor":35,"kind":11,"station_id":29,"system_id":5,"story":true,"reward":0,"bonus":0,"briefing_events":[]}}
const MAC_VALUES:={"scope":"nehma_station_visit34","mission34":{"campaign_cursor":34,"kind":11,"station_id":30,"system_id":2,"story":true,"reward":0,"bonus":0,"briefing_events":[],"result_events":[{"speaker_id":1,"text_id":1966,"voice_event_id":364},{"speaker_id":0,"text_id":1967,"voice_event_id":365},{"speaker_id":1,"text_id":1968,"voice_event_id":371},{"speaker_id":0,"text_id":1969,"voice_event_id":372},{"speaker_id":1,"text_id":1970,"voice_event_id":373},{"speaker_id":0,"text_id":1971,"voice_event_id":374},{"speaker_id":1,"text_id":1972,"voice_event_id":375},{"speaker_id":0,"text_id":1973,"voice_event_id":376},{"speaker_id":1,"text_id":1974,"voice_event_id":377},{"speaker_id":0,"text_id":1975,"voice_event_id":378},{"speaker_id":1,"text_id":1976,"voice_event_id":366},{"speaker_id":0,"text_id":1977,"voice_event_id":367},{"speaker_id":1,"text_id":1978,"voice_event_id":368},{"speaker_id":0,"text_id":1979,"voice_event_id":369},{"speaker_id":1,"text_id":1980,"voice_event_id":370}],"completion":{"result_mode":1,"requires_landed_target":true,"completed_on_result_open":true,"intermediate_next_keeps_cursor":34,"final_next_requires_all_modal_acknowledgements":true,"final_next_advances_to_cursor":35,"reward_credits":0,"stays_landed_station_id":30,"cargo_or_equipment_change":false,"extra_blueprint_change":false,"extra_system_access_granted":false}},"world":{"authored_cast":[],"authored_radio_events":[],"selected_kind11_actor_count":0},"next_mission":{"campaign_cursor":35,"kind":11,"station_id":29,"system_id":5,"story":true,"reward":0,"bonus":0,"briefing_events":[]}}
const SPANS:={"factory35_entry":[872174,4],"factory35":[863293,38],"brief34_35_counts":[1529722,8],"result34_count":[1530378,4],"result34_pairs":[1523090,120],"result34_voices":[1536826,120],"radio34_entry":[104622,4]}
const MAC_SPANS:={"factory35_entry":[871542,4],"factory35":[862661,38],"brief34_35_counts":[1554738,8],"result34_count":[1555394,4],"result34_pairs":[1548106,120],"result34_voices":[1561762,120],"radio34_entry":[104622,4]}

static func parameters(data: Variant) -> bool:
	return Equal.equal_value(data,VALUES) or Equal.equal_value(data,MAC_VALUES)

static func validate(data: Variant, proof: Variant, executable_bytes: int, architecture: String, arrival: Dictionary, crystals: Variant) -> String:
	if not parameters(data):return "Unsupported Néhma visit declarations"
	if architecture!="x86_64":return "Unsupported Néhma visit source architecture"
	var app_store: bool=Equal.equal_value(data,VALUES)
	if not Equal.equal_value(crystals,Void.VALUES if app_store else Void.MAC_VALUES):return "Disconnected cursor34 prerequisite"
	var origin: Variant=arrival.get("provenance",{}).get("actor")
	if not Fonts.extent(origin,"offset","bytes",[315],executable_bytes):return "Néhma visit source anchor is missing"
	return "" if Layouts.matches(proof,int(origin.offset),executable_bytes,[SPANS if app_store else MAC_SPANS]) else "Disconnected Néhma visit source declaration"
