extends RefCounted
## Source declarations for an offered ordinary Hangar ship exchange.
## This capability is intentionally unwired; current ship instance state, mutable
## ship stock, and save ownership must exist before exposing the action.
const Equal=preload("res://src/content/opening_escape_definitions.gd")
const Fonts=preload("res://src/content/font_definitions.gd")
const Layouts=preload("res://src/content/declaration_layouts.gd")
const Shopping=preload("res://src/content/ordinary_shopping_definitions.gd")
const VALUES := {"scope":"ordinary_hangar_offered_ship_purchase","quotes":{"offer":"retained_offer_instance","current":"retained_current_ship_instance","preflight":"offer_lte_wallet_plus_current","shortfall":"offer_minus_wallet_minus_current","sell_credit_percent":100,"sell_wallet_delta":"current_minus_offer","keep_wallet_delta":"negative_offer","keep_requires_full_offer_affordability":true},"entry":{"clone_without_override_preserves_instance_quote":true,"fresh_career_current_ship_id":10,"fresh_career_quote_base":"catalogue_ship_price","fresh_career_quote_divisor":1.25,"fresh_career_quote_arithmetic":"float32_division_then_truncate_i32","hangar_current_quote_refresh":"on_hangar_model_rebuild","hangar_refresh_requires_current_station":true,"hangar_refresh_requires_positive_existing_quote":true,"hangar_refresh_quote_base":"catalogue_ship_price","hangar_refresh_pricing_owner":"ordinary_base_station_stock.ships","fresh_catalogue_generated_offer_tags":[]},"text_ids":{"buy_prompt":293,"sell_or_keep_prompt":316,"sell_label":319,"keep_label":320,"insufficient_credits":192,"insufficient_credits_legacy_upsell":123,"passengers":325,"restricted_sale":314,"same_ship":318,"duplicate_parked_old_type":317},"choices":{"sell_result":0,"keep_result":1,"dismissal_changes_state":false},"guards":{"passenger_count_must_be_zero":true,"restricted_sale_career_state":77,"restricted_sale_current_ship_id":37,"offered_ship_id_must_differ":true,"keep_requires_no_parked_old_ship_type":true,"cargo_capacity_rejection_during_exchange":false},"transfer":{"owned_cargo_source":"committed_hangar_rows","new_ship_source":"catalogue_prototype_for_offer_id","new_ship_affiliation_source":"offered_instance","new_ship_quote":"locally_recalculated_after_offer_affiliation","debit_quote_source":"retained_offered_instance","cargo_instances_keep_quantity_price_and_protection":true,"installed_instances_cloned":true,"installed_instances_keep_quantity":true,"installed_slot_order":"old_ship_order","installed_fit":"first_compatible_free_slot","failed_installed_fit":"same_instance_to_new_cargo","purchased_ship_tags_source":"offered_instance","former_ship_tags_source":"old_current_instance","old_live_pools_copied":false},"stock":{"sell":"replace_purchased_offer_at_same_index_with_stripped_old_ship","keep":"remove_purchased_offer_and_park_stripped_old_ship","former_ship_affiliation_source":"old_current_instance","sell_replacement_quote":"locally_recalculated"},"commit":{"current_ship_replaced_once":true,"ship_derived_stats_recomputed":true,"hangar_rows_rebuilt":true}}
const SPANS := {"purchase_preflight":[-134575,838],"choice_and_transfer":[-144254,989],"ship_exchange":[-143205,1796],"current_ship_setter":[872734,73],"current_ship_getter":[858758,13],"ordinary_departure_reset":[432297,126],"fresh_player_restore":[334997,128],"new_ship_cache_refresh":[335134,126],"hull_upgrade_tags":[730112,59],"ships_bin_catalogue":[-677542,430],"ship_constructor_entry":[727934,10],"ship_instance_constructor":[727944,260],"ship_instance_clone":[733492,182],"ship_clone_price_guard":[733464,28],"new_career_quote":[733674,48],"new_career_current_ship":[883792,51],"ordinary_ship_factory":[-242998,3820],"current_quote_reprice":[733722,206],"hangar_quote_refresh":[-173140,4582],"hangar_owner_create":[440227,46]}
const MAC_SPANS := {"purchase_preflight":[-134197,838],"choice_and_transfer":[-143770,989],"ship_exchange":[-142721,1796],"current_ship_setter":[872102,73],"current_ship_getter":[858126,13],"ordinary_departure_reset":[431869,126],"fresh_player_restore":[335297,128],"new_ship_cache_refresh":[335434,126],"hull_upgrade_tags":[729488,59],"ships_bin_catalogue":[-671654,430],"ship_constructor_entry":[727310,10],"ship_instance_constructor":[727320,260],"ship_instance_clone":[732860,182],"ship_clone_price_guard":[732832,28],"new_career_quote":[733042,48],"new_career_current_ship":[883160,51],"ordinary_ship_factory":[-241510,3352],"current_quote_reprice":[733090,206],"hangar_quote_refresh":[-172648,4582],"hangar_owner_create":[439715,46]}

static func parameters(data: Variant) -> bool:
	if not data is Dictionary or data.size()!=VALUES.size()+1 or not data.get("provenance") is Dictionary:return false
	for key in VALUES:
		if not Equal.equal_value(data.get(key),VALUES[key]):return false
	return true

static func validate(data: Variant, source_bytes: int, architecture: String, arrival: Dictionary, ordinary_shopping: Variant) -> String:
	if not parameters(data):return "Unsupported ordinary ship purchase declarations"
	if architecture!="x86_64" or not Shopping.parameters(ordinary_shopping):return "Disconnected ordinary ship purchase source"
	var source: Variant=arrival.get("provenance")
	if not source is Dictionary:return "Ordinary ship purchase source anchor is missing"
	var origin: Variant=source.get("actor")
	if not Fonts.extent(origin,"offset","bytes",[315],source_bytes):return "Ordinary ship purchase source anchor is missing"
	return "" if Layouts.matches(data.provenance,int(origin.offset),source_bytes,[SPANS,MAC_SPANS]) else "Invalid ordinary ship purchase extents"
