extends RefCounted
## Selected component history, generated by the ordinary stock/contact owners.
## This is deliberately not an earned career fixture.
const LoungeCache=preload("res://src/simulation/lounge_cache.gd")
const Random=preload("res://src/simulation/seeded_random.gd")
const ORDER=[55,45,48]
const SETTINGS={"difficulty":0.5,"valkyrie_owned":false,"supernova_owned":false,
	"energy_availability_percent":0,"missile_availability_percent":0,"ship_price_percent":0}
var error:=""

func create(bindings: RefCounted,cat: RefCounted,library: RefCounted) -> RefCounted:
	error=""
	var locations:=LoungeCache.new()
	if not locations.configure(bindings):error=locations.error;return null
	var random:=Random.new();random.seed_from(5)
	var state: Dictionary=random.snapshot()
	for station_id in ORDER:
		var context:={"station_id":station_id,"campaign_cursor":24,"rank":0,
			"reputation":{"axes":[0,0],"override":-1}}
		if not locations.select_location(bindings,cat,library,context,SETTINGS,state,1700000000+station_id):
			error=locations.error;return null
		state=locations.snapshot().random
	var saved: Dictionary=locations.snapshot()
	if saved.locations.map(func(row):return int(row.station_id))!=ORDER or saved.current_station_id!=48:
		error="Selected Sahi history lost its three generated visits";return null
	for station_id in ORDER:
		var retained: Dictionary=locations.location(station_id)
		if not retained.has("stock") or not retained.has("population"):
			error="Selected Sahi history lacks generated stock or contacts";return null
	return locations
